In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

## **input data และจัดการข้อมูล**

In [ ]:
data = pd.read_csv('m31.csv')
data

classification     ra    dec        u        b        v        r  \
0                      GCs   8.19  39.58    14.75    14.56    13.81    13.21   
1                      GCs  11.12  41.36    15.52    15.05    14.16    13.57   
2                      GCs  10.25  41.23    15.88    15.40    14.22    13.56   
3                      GCs  10.25  40.60    15.21    15.06    14.25    13.62   
4                      GCs  10.69  41.24    15.76    14.97    14.47    13.29   
...                    ...    ...    ...      ...      ...      ...      ...   
2055  Controversial object  10.70  41.31  9999.00  9999.00  9999.00  9999.00   
2056  Controversial object  10.65  41.22  9999.00  9999.00  9999.00  9999.00   
2057  Controversial object  10.61  41.30  9999.00  9999.00  9999.00  9999.00   
2058  Controversial object  10.64  40.93  9999.00  9999.00  9999.00  9999.00   
2059  Controversial object   9.73  41.17  9999.00  9999.00  9999.00  9999.00   

            i        j        h        k       Vr  
0       12.68    11.85    11.13    11.04   -332.0  
1       12.93    11.95    11.23    11.07   -165.0  
2       12.57    11.66    10.91    10.77   -451.0  
3       13.23    12.44    11.78    11.69   -274.0  
4       13.23    12.22    11.51    11.38   -470.0  
...       ...      ...      ...      ...      ...  
2055  9999.00    14.60    14.74  9999.00   -210.0  
2056  9999.00    16.42    14.73  9999.00  99999.0  
2057  9999.00  9999.00  9999.00  9999.00  99999.0  
2058  9999.00  9999.00  9999.00  9999.00  99999.0  
2059  9999.00  9999.00  9999.00  9999.00  99999.0  

[2060 rows x 12 columns]

In [ ]:
data.columns

Index(['classification', 'ra', 'dec', 'u', 'b', 'v', 'r', 'i', 'j', 'h', 'k',
       'Vr'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2060 entries, 0 to 2059
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   classification  2060 non-null   object 
 1   ra              2060 non-null   float64
 2   dec             2060 non-null   float64
 3   u               2060 non-null   float64
 4   b               2060 non-null   float64
 5   v               2060 non-null   float64
 6   r               2060 non-null   float64
 7   i               2060 non-null   float64
 8   j               2060 non-null   float64
 9   h               2060 non-null   float64
 10  k               2060 non-null   float64
 11  Vr              2060 non-null   float64
dtypes: float64(11), object(1)
memory usage: 193.2+ KB


In [ ]:
data['classification'].unique()

array(['GCs', 'Candidate GCs', 'Controversial object', 'galaxy'],
      dtype=object)

In [ ]:
#ohenc1 = OneHotEncoder(sparse=False)
#m1=ohenc1.fit_transform(data[['classification']])
#m1

In [ ]:
#ohenc1.categories_

In [ ]:
data[:3]

classification     ra    dec      u      b      v      r      i      j  \
0            GCs   8.19  39.58  14.75  14.56  13.81  13.21  12.68  11.85   
1            GCs  11.12  41.36  15.52  15.05  14.16  13.57  12.93  11.95   
2            GCs  10.25  41.23  15.88  15.40  14.22  13.56  12.57  11.66   

       h      k     Vr  
0  11.13  11.04 -332.0  
1  11.23  11.07 -165.0  
2  10.91  10.77 -451.0

In [ ]:
plot_kws = {'scatter_kws': {'alpha': 0.4}}

In [ ]:
X = data[['ra', 'dec', 'u', 'b', 'v', 'r', 'i', 'j', 'h', 'k', 'Vr']]
y = data[['classification']]

# **data split**

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X = data[['ra', 'dec', 'u', 'b', 'v', 'r', 'i', 'j', 'h', 'k', 'Vr']]
y = data[['classification']]

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(X,y,
                                                     test_size=0.2,
                                                     random_state=8)

# **Random forest algorithm**

In [ ]:
model_rf = RandomForestClassifier(n_estimators=100,random_state=None) #ไฮเปอร์พารามิเตอร์เริ่มต้นของ RF
model_rf.fit(X_train, y_train)


<ipython-input-15-19c22e00434f>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model_rf.fit(X_train, y_train)


RandomForestClassifier()

In [ ]:
predictions = np.nan_to_num(X)
predictions

array([[ 8.1900e+00,  3.9580e+01,  1.4750e+01, ...,  1.1130e+01,
         1.1040e+01, -3.3200e+02],
       [ 1.1120e+01,  4.1360e+01,  1.5520e+01, ...,  1.1230e+01,
         1.1070e+01, -1.6500e+02],
       [ 1.0250e+01,  4.1230e+01,  1.5880e+01, ...,  1.0910e+01,
         1.0770e+01, -4.5100e+02],
       ...,
       [ 1.0610e+01,  4.1300e+01,  9.9990e+03, ...,  9.9990e+03,
         9.9990e+03,  9.9999e+04],
       [ 1.0640e+01,  4.0930e+01,  9.9990e+03, ...,  9.9990e+03,
         9.9990e+03,  9.9999e+04],
       [ 9.7300e+00,  4.1170e+01,  9.9990e+03, ...,  9.9990e+03,
         9.9990e+03,  9.9999e+04]])

In [ ]:
model_rf.fit(X_train,y_train)

<ipython-input-17-886240159eb4>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model_rf.fit(X_train,y_train)


RandomForestClassifier()

In [ ]:
y_pred = model_rf.predict(X_test)

In [ ]:
accuracy_score(y_pred, y_test)

0.8058252427184466

In [ ]:
#score ของ random forest
model_rf.score(X_train,y_train)
model_rf.score(X_test,y_test)


0.8058252427184466

In [ ]:
confusion_matrix(y_test, y_pred)

array([[ 40,  12,   1,   2],
       [ 12, 133,  13,   2],
       [  7,  26,  95,   0],
       [  2,   3,   0,  64]])

In [ ]:
recall_score(y_test, y_pred, average=None)

array([0.72727273, 0.83125   , 0.7421875 , 0.92753623])

In [ ]:
precision_score(y_test, y_pred, average=None)

array([0.6557377 , 0.76436782, 0.87155963, 0.94117647])

In [ ]:
f1_score(y_test, y_pred, average=None)

array([0.68965517, 0.79640719, 0.80168776, 0.93430657])

In [ ]:
#ป้อนข้อมูลที่ต้องการตรวจสอบลงไปแล้วให้แสดงผลว่ามันเป็นอะไร โดยมี 10 feature
model_rf.predict([[9.18,39.58,20.08,19.35,18.24,18.24,17.40,16.69,21.31,212.44,124.00]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['Controversial object'], dtype=object)

# **GradientBoosting algorithm**

In [ ]:
model_gb = GradientBoostingClassifier(n_estimators=100,random_state=None)
model_gb.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier()

In [ ]:
y_pred_gb = model_gb.predict(X_test)

In [ ]:
accuracy_score(y_pred_gb, y_test)

0.8252427184466019

In [ ]:
model_gb.score(X_train,y_train)
model_gb.score(X_test,y_test)

0.8252427184466019

In [ ]:
y_predgb = model_gb.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_pred_gb)

array([[ 41,  10,   0,   4],
       [ 12, 139,   8,   1],
       [  5,  26,  97,   0],
       [  4,   0,   2,  63]])

In [ ]:
recall_score(y_test, y_pred_gb, average=None)

array([0.74545455, 0.86875   , 0.7578125 , 0.91304348])

In [ ]:
precision_score(y_test, y_pred_gb, average=None)

array([0.66129032, 0.79428571, 0.90654206, 0.92647059])

In [ ]:
f1_score(y_test, y_pred_gb, average=None)

array([0.7008547 , 0.82985075, 0.82553191, 0.91970803])

# **AdaBoost Algolrithm**


In [ ]:
model_ad = AdaBoostClassifier(n_estimators=100)
model_ad.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=100)

In [ ]:
y_pred_ad = model_ad.predict(X_test)

In [ ]:
model_ad.score(X_train,y_train)
model_ad.score(X_test,y_test)

0.6237864077669902

In [ ]:
confusion_matrix(y_test, y_pred_ad)

array([[33, 12,  1,  9],
       [24, 81, 44, 11],
       [ 7, 26, 85, 10],
       [ 4,  5,  2, 58]])

In [ ]:
recall_score(y_test, y_pred_ad, average=None)

array([0.6       , 0.50625   , 0.6640625 , 0.84057971])

In [ ]:
precision_score(y_test, y_pred_ad, average=None)

array([0.48529412, 0.65322581, 0.64393939, 0.65909091])

In [ ]:
f1_score(y_test, y_pred_ad, average=None)

array([0.53658537, 0.57042254, 0.65384615, 0.7388535 ])

# **Bagging algorithm**

In [ ]:
model_bg = BaggingClassifier(n_estimators=100,random_state=None)
model_bg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(n_estimators=100)

In [ ]:
y_pred_bg = model_bg.predict(X_test)

In [ ]:
model_bg.score(X_train,y_train)
model_bg.score(X_test,y_test)

0.7864077669902912

In [ ]:
confusion_matrix(y_test, y_pred_bg)

array([[ 38,  13,   0,   4],
       [ 16, 127,  17,   0],
       [  7,  25,  96,   0],
       [  4,   0,   2,  63]])

In [ ]:
recall_score(y_test, y_pred_bg,average=None)

array([0.69090909, 0.79375   , 0.75      , 0.91304348])

In [ ]:
precision_score(y_test, y_pred_bg, average=None)

array([0.58461538, 0.76969697, 0.83478261, 0.94029851])

In [ ]:
f1_score(y_test, y_pred_bg, average=None)

array([0.63333333, 0.78153846, 0.79012346, 0.92647059])

# **ประเมินคุณภาพโมเดลทั้งสอง**

In [ ]:
alogo = [
    [RandomForestClassifier(), 'RandomForestClassifier'],
    [GradientBoostingClassifier(), 'GradientBoostingClassifier'],
    [BaggingClassifier(),'BaggingClassifier'],
    [AdaBoostClassifier(),'AdaBoostClassifier'],
]
model_score = []
for a in alogo :
    model = a[0]
    model.fit(X_train,y_train)
    score = model.score(X_test, y_test)
    model_score.append([score, a[1]])
    y_predicted = model.predict(X_test)
    print(f'{a[1]:20} score : {score:.04f}')
    print(metrics.confusion_matrix(y_test,y_predicted))
    print(metrics.classification_report(y_test, y_predicted))
    print('-'*100)

print(model_score)
print(f'best score = {max(model_score)}')

<ipython-input-49-f96f5ddb76d4>:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)


RandomForestClassifier score : 0.7937
[[ 39  11   1   4]
 [ 13 133  13   1]
 [  7  27  94   0]
 [  5   3   0  61]]
                      precision    recall  f1-score   support

       Candidate GCs       0.61      0.71      0.66        55
Controversial object       0.76      0.83      0.80       160
                 GCs       0.87      0.73      0.80       128
              galaxy       0.92      0.88      0.90        69

            accuracy                           0.79       412
           macro avg       0.79      0.79      0.79       412
        weighted avg       0.80      0.79      0.80       412

----------------------------------------------------------------------------------------------------


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier score : 0.8252
[[ 41  10   0   4]
 [ 12 139   8   1]
 [  5  26  97   0]
 [  4   0   2  63]]
                      precision    recall  f1-score   support

       Candidate GCs       0.66      0.75      0.70        55
Controversial object       0.79      0.87      0.83       160
                 GCs       0.91      0.76      0.83       128
              galaxy       0.93      0.91      0.92        69

            accuracy                           0.83       412
           macro avg       0.82      0.82      0.82       412
        weighted avg       0.83      0.83      0.83       412

----------------------------------------------------------------------------------------------------
BaggingClassifier    score : 0.7743
[[ 41  11   1   2]
 [ 18 126  14   2]
 [  7  32  89   0]
 [  4   2   0  63]]
                      precision    recall  f1-score   support

       Candidate GCs       0.59      0.75      0.66        55
Controversial object       0.74      0.79  

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier   score : 0.6869
[[37 15  1  2]
 [20 98 37  5]
 [ 7 21 88 12]
 [ 3  4  2 60]]
                      precision    recall  f1-score   support

       Candidate GCs       0.55      0.67      0.61        55
Controversial object       0.71      0.61      0.66       160
                 GCs       0.69      0.69      0.69       128
              galaxy       0.76      0.87      0.81        69

            accuracy                           0.69       412
           macro avg       0.68      0.71      0.69       412
        weighted avg       0.69      0.69      0.69       412

----------------------------------------------------------------------------------------------------
[[0.7936893203883495, 'RandomForestClassifier'], [0.8252427184466019, 'GradientBoostingClassifier'], [0.7742718446601942, 'BaggingClassifier'], [0.6868932038834952, 'AdaBoostClassifier']]
best score = [0.8252427184466019, 'GradientBoostingClassifier']


In [ ]:
!pip install eli5

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.2/216.2 kB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for eli5: filename=eli5-0.13.0-py2.py3-none-any.whl size=107730 sha256=8ef847e9c55644e0ad8833fb45f7a3b582b4b7ce91f6a33f676ee8dfadf0bf5a
  Stored in directory: /root/.cache/pip/wheels/b8/58/ef/2cf4c306898c2338d51540e0922c8e0d6028e07007085c0004
Successfully built eli5


In [ ]:
import eli5
from eli5.sklearn import PermutationImportance

In [ ]:
perm = PermutationImportance(model_rf, random_state=13).fit(X_test, y_test)

In [ ]:
eli5.show_weights(perm, feature_names = X_test.columns.tolist(), top=100)

# **Hyperparameter_tuning RF**




In [ ]:
#Hyperparameter tuning model_RF
random_state_range = np.arange(1,12,1)
n_estimator_range = np.arange(10,210,10)
param_grid = dict(random_state=random_state_range, n_estimators =n_estimator_range)

rf = RandomForestClassifier()


grid_rf = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5 )

In [ ]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
grid_rf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200]),
                         'random_state': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])})

In [ ]:
print("the best hyperparameters RF model are %s with a score of %0.2f"
      % (grid_rf.best_params_, grid_rf.best_score_))

the best hyperparameters RF model are {'n_estimators': 200, 'random_state': 11} with a score of 0.76


# **dataframe of grid search parameter rf**

In [ ]:
grid_rf_results = pd.concat([pd.DataFrame(grid_rf.cv_results_["params"]),
                          pd.DataFrame(grid_rf.cv_results_["mean_test_score"],
                                       columns=["Accuracy"])],axis=1)
grid_rf_results.head()


n_estimators  random_state  Accuracy
0            10             1  0.712963
1            10             2  0.718431
2            10             3  0.715990
3            10             4  0.723277
4            10             5  0.705692

In [ ]:
grid_rf_contour = grid_rf_results.groupby(['random_state','n_estimators']).mean()
grid_rf_contour

Accuracy
random_state n_estimators          
1            10            0.712963
             20            0.732987
             30            0.742096
             40            0.739066
             50            0.746352
...                             ...
11           160           0.751797
             170           0.751797
             180           0.757858
             190           0.757252
             200           0.758471

[220 rows x 1 columns]

# **pivoting the data RF**

In [ ]:
grid_rf_reset = grid_rf_contour.reset_index()
grid_rf_reset.columns = ['random_state', 'n_estimators', 'Accuracy']
grid_rf_pivot = grid_rf_reset.pivot('random_state', 'n_estimators')
grid_rf_pivot

<ipython-input-60-5815b035c33d>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  grid_rf_pivot = grid_rf_reset.pivot('random_state', 'n_estimators')


Accuracy                                                    \
n_estimators       10        20        30        40        50        60    
random_state                                                               
1             0.712963  0.732987  0.742096  0.739066  0.746352  0.743316   
2             0.718431  0.741485  0.747551  0.746342  0.745733  0.750581   
3             0.715990  0.733606  0.743312  0.753013  0.754825  0.754223   
4             0.723277  0.741477  0.746339  0.752414  0.745742  0.750592   
5             0.705692  0.729358  0.731773  0.739055  0.739659  0.745727   
6             0.719648  0.732388  0.739678  0.742702  0.742697  0.744522   
7             0.725709  0.737841  0.740274  0.748761  0.750581  0.756049   
8             0.708102  0.726306  0.732989  0.740262  0.737222  0.749367   
9             0.717819  0.738449  0.737847  0.739672  0.742695  0.741483   
10            0.712357  0.732980  0.732372  0.737821  0.734181  0.738434   
11            0.728724  0.736634  0.740273  0.743911  0.752410  0.749984   

                                                                          \
n_estimators       70        80        90        100       110       120   
random_state                                                               
1             0.742715  0.749994  0.751213  0.748783  0.749382  0.749988   
2             0.749971  0.751195  0.751185  0.750585  0.750581  0.754221   
3             0.753015  0.753013  0.753018  0.749382  0.756664  0.753626   
4             0.745145  0.749382  0.748776  0.749984  0.752412  0.754238   
5             0.746950  0.748157  0.748763  0.748767  0.748155  0.745119   
6             0.739061  0.742702  0.744521  0.743308  0.746950  0.746947   
7             0.753015  0.750587  0.749369  0.754829  0.751799  0.753005   
8             0.750583  0.750581  0.753613  0.751797  0.753617  0.753009   
9             0.738445  0.746342  0.749984  0.751196  0.751193  0.747553   
10            0.738432  0.743896  0.746326  0.745114  0.746322  0.746934   
11            0.750592  0.751803  0.751198  0.753621  0.752407  0.754835   

                                                                          \
n_estimators       130       140       150       160       170       180   
random_state                                                               
1             0.754840  0.752412  0.756655  0.754225  0.754230  0.751193   
2             0.754223  0.754827  0.754829  0.756043  0.754829  0.754831   
3             0.755446  0.751198  0.753626  0.754842  0.754242  0.754240   
4             0.749982  0.751193  0.753619  0.751189  0.751191  0.752399   
5             0.748759  0.749369  0.745729  0.749367  0.751790  0.748157   
6             0.750587  0.749981  0.754230  0.753621  0.750585  0.752407   
7             0.753011  0.754229  0.751795  0.753617  0.754229  0.749981   
8             0.749365  0.751189  0.751193  0.752403  0.751189  0.751187   
9             0.754225  0.751797  0.752401  0.753615  0.754221  0.754827   
10            0.748146  0.745723  0.749367  0.749971  0.748757  0.746934   
11            0.751797  0.753619  0.753013  0.751797  0.751797  0.757858   

                                  
n_estimators       190       200  
random_state                      
1             0.750581  0.747547  
2             0.751797  0.753611  
3             0.750592  0.754234  
4             0.751795  0.753615  
5             0.746337  0.746341  
6             0.752405  0.751187  
7             0.749369  0.751799  
8             0.750587  0.752409  
9             0.756039  0.757861  
10            0.747538  0.746326  
11            0.757252  0.758471

In [ ]:
x_rf = grid_rf_pivot.columns.levels[1].values
y_rf = grid_rf_pivot.index.values
z_rf = grid_rf_pivot.values

# **2D Contour Plot RF**

In [ ]:
import plotly.graph_objects as go

# X and Y axes labels
layout = go.Layout(
            xaxis=go.layout.XAxis(
              title=go.layout.xaxis.Title(
              text='n_estimators')
             ),
             yaxis=go.layout.YAxis(
              title=go.layout.yaxis.Title(
              text='random_state')
            ) )

fig = go.Figure(data = [go.Contour(z=z_rf, x=x_rf, y=y_rf)], layout=layout )

fig.update_layout(title='Hyperparameter tuning', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()

# **3D Surface Plot RF**

In [ ]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z_rf, y=y_rf, x=x_rf)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='random_state',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()

# **Hyperparameter tuning GD**

In [ ]:
#Hyperparameter tuning model_GD
random_state_range = np.arange(1,12,1)
n_estimator_range = np.arange(10,210,10)
param_grid = dict(random_state=random_state_range, n_estimators =n_estimator_range)

gd = GradientBoostingClassifier()


grid_gd = GridSearchCV(estimator=gd, param_grid=param_grid, cv=5 )

In [ ]:
grid_gd.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning:


GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200]),
                         'random_state': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])})

In [ ]:
print("the best hyperparameters GD model are %s with a score of %0.2f"
      % (grid_gd.best_params_, grid_gd.best_score_))

the best hyperparameters GD model are {'n_estimators': 190, 'random_state': 11} with a score of 0.76


# **dataframe of grid search parameter gd**

In [ ]:
grid_gd_results = pd.concat([pd.DataFrame(grid_gd.cv_results_["params"]),
                          pd.DataFrame(grid_gd.cv_results_["mean_test_score"],
                                       columns=["Accuracy"])],axis=1)
grid_gd_results.head()

n_estimators  random_state  Accuracy
0            10             1  0.723281
1            10             2  0.723281
2            10             3  0.723281
3            10             4  0.723281
4            10             5  0.723281

In [ ]:
grid_gd_contour = grid_gd_results.groupby(['random_state','n_estimators']).mean()
grid_gd_contour

Accuracy
random_state n_estimators          
1            10            0.723281
             20            0.740890
             30            0.753628
             40            0.749990
             50            0.754846
...                             ...
11           160           0.757874
             170           0.759092
             180           0.756666
             190           0.760308
             200           0.757878

[220 rows x 1 columns]

# **pivoting the data GD**

In [ ]:
grid_gd_reset = grid_gd_contour.reset_index()
grid_gd_reset.columns = ['random_state', 'n_estimators', 'Accuracy']
grid_gd_pivot = grid_gd_reset.pivot('random_state', 'n_estimators')
grid_gd_pivot

<ipython-input-69-1eedb9234d0a>:3: FutureWarning:

In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.



Accuracy                                                    \
n_estimators       10        20        30        40        50        60    
random_state                                                               
1             0.723281  0.740890  0.753628  0.749990  0.754846  0.757274   
2             0.723281  0.742100  0.749386  0.750596  0.754240  0.756668   
3             0.723281  0.742708  0.749386  0.751202  0.754238  0.757274   
4             0.723281  0.742098  0.751204  0.747566  0.753026  0.756668   
5             0.723281  0.743316  0.749386  0.751204  0.754242  0.756668   
6             0.723281  0.740282  0.752416  0.749990  0.753026  0.754849   
7             0.723281  0.742708  0.749386  0.751810  0.754846  0.756668   
8             0.723281  0.742708  0.749386  0.751202  0.754238  0.757274   
9             0.723281  0.743316  0.749386  0.750596  0.753634  0.756668   
10            0.723281  0.742100  0.749386  0.749990  0.753026  0.756668   
11            0.723281  0.744528  0.750598  0.748172  0.753028  0.754849   

                                                                          \
n_estimators       70        80        90        100       110       120   
random_state                                                               
1             0.757268  0.750596  0.752412  0.754842  0.751810  0.753026   
2             0.756662  0.754838  0.754837  0.757266  0.753626  0.754238   
3             0.757268  0.754837  0.754837  0.756660  0.754232  0.753632   
4             0.755450  0.749988  0.751200  0.753630  0.748172  0.749994   
5             0.757268  0.755444  0.754837  0.756660  0.754840  0.754240   
6             0.756056  0.753020  0.754837  0.756054  0.754838  0.754846   
7             0.756660  0.754838  0.754837  0.757266  0.754232  0.754238   
8             0.756660  0.754838  0.754837  0.757266  0.754232  0.753630   
9             0.757268  0.754230  0.754837  0.757266  0.754840  0.754846   
10            0.756660  0.754838  0.754230  0.756660  0.753626  0.754240   
11            0.754238  0.751808  0.751806  0.754842  0.751810  0.752421   

                                                                          \
n_estimators       130       140       150       160       170       180   
random_state                                                               
1             0.751204  0.751200  0.753630  0.753024  0.755454  0.753026   
2             0.751204  0.750594  0.754234  0.753628  0.758482  0.757268   
3             0.751812  0.750594  0.754234  0.753022  0.757876  0.755450   
4             0.749992  0.751806  0.752416  0.753022  0.753026  0.752418   
5             0.752420  0.751810  0.755450  0.754844  0.759090  0.757876   
6             0.752418  0.750594  0.756054  0.756660  0.759696  0.757270   
7             0.752418  0.751202  0.755448  0.754236  0.759090  0.757876   
8             0.751810  0.750594  0.754840  0.753628  0.758482  0.756662   
9             0.753026  0.751810  0.756056  0.754844  0.759698  0.756664   
10            0.751812  0.751202  0.755450  0.754844  0.759090  0.757878   
11            0.751814  0.752416  0.756056  0.757874  0.759092  0.756666   

                                  
n_estimators       190       200  
random_state                      
1             0.754243  0.751814  
2             0.759092  0.756660  
3             0.757880  0.756662  
4             0.754848  0.751814  
5             0.759700  0.757268  
6             0.758488  0.756664  
7             0.760306  0.757876  
8             0.758486  0.757268  
9             0.759094  0.757876  
10            0.759702  0.757876  
11            0.760308  0.757878

In [ ]:
x_gd = grid_gd_pivot.columns.levels[1].values
y_gd = grid_gd_pivot.index.values
z_gd = grid_gd_pivot.values

# **2D Contour Plot GD**

In [ ]:
import plotly.graph_objects as go

# X and Y axes labels
layout = go.Layout(
            xaxis=go.layout.XAxis(
              title=go.layout.xaxis.Title(
              text='n_estimators')
             ),
             yaxis=go.layout.YAxis(
              title=go.layout.yaxis.Title(
              text='random_state')
            ) )

fig = go.Figure(data = [go.Contour(z=z_gd, x=x_gd, y=y_gd)], layout=layout )

fig.update_layout(title='Hyperparameter tuning', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()

# **3D Surface Plot GD**

In [ ]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z_gd, y=y_gd, x=x_gd)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='random_state',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()

# **Hyperparameter tuning AdaBoost**




In [ ]:
#Hyperparameter tuning model_AD
random_state_range = np.arange(1,12,1)
n_estimator_range = np.arange(10,210,10)
param_grid = dict(random_state=random_state_range, n_estimators =n_estimator_range)

ad = AdaBoostClassifier()


grid_ad = GridSearchCV(estimator=ad, param_grid=param_grid, cv=5 )

In [ ]:
grid_ad.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143

In [ ]:
print("the best hyperparameters RF model are %s with a score of %0.2f"
      % (grid_ad.best_params_, grid_ad.best_score_))

# **dataframe of grid search parameter ad**

In [ ]:
grid_ad_results = pd.concat([pd.DataFrame(grid_ad.cv_results_["params"]),
                          pd.DataFrame(grid_ad.cv_results_["mean_test_score"],
                                       columns=["Accuracy"])],axis=1)
grid_ad_results.head()

n_estimators  random_state  Accuracy
0            10             1  0.688124
1            10             2  0.688124
2            10             3  0.688124
3            10             4  0.688124
4            10             5  0.688124

In [ ]:
grid_ad_contour = grid_ad_results.groupby(['random_state','n_estimators']).mean()
grid_ad_contour

Accuracy
random_state n_estimators          
1            10            0.688124
             20            0.685692
             30            0.678989
             40            0.658981
             50            0.650493
...                             ...
11           160           0.614070
             170           0.620744
             180           0.615290
             190           0.613466
             200           0.619538

[220 rows x 1 columns]

# **pivoting the data AD**



In [ ]:
grid_ad_reset = grid_ad_contour.reset_index()
grid_ad_reset.columns = ['random_state', 'n_estimators', 'Accuracy']
grid_ad_pivot = grid_ad_reset.pivot('random_state', 'n_estimators')
grid_ad_pivot

<ipython-input-91-9d485bf96f7b>:3: FutureWarning:

In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.



Accuracy                                                    \
n_estimators       10        20        30        40        50        60    
random_state                                                               
1             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
2             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
3             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
4             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
5             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
6             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
7             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
8             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
9             0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
10            0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   
11            0.688124  0.685692  0.678989  0.658981  0.650493  0.647466   

                                                                          \
n_estimators       70        80        90        100       110       120   
random_state                                                               
1             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
2             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
3             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
4             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
5             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
6             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
7             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
8             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
9             0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
10            0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   
11            0.637771  0.629268  0.624405  0.618326  0.621971  0.603752   

                                                                        \
n_estimators       130       140       150      160       170      180   
random_state                                                             
1             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
2             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
3             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
4             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
5             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
6             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
7             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
8             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
9             0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
10            0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   
11            0.623159  0.610412  0.620731  0.61407  0.620744  0.61529   

                                  
n_estimators       190       200  
random_state                      
1             0.613466  0.619538  
2             0.613466  0.619538  
3             0.613466  0.619538  
4             0.613466  0.619538  
5             0.613466  0.619538  
6             0.613466  0.619538  
7             0.613466  0.619538  
8             0.613466  0.619538  
9             0.613466  0.619538  
10            0.613466  0.619538  
11            0.613466  0.619538

In [ ]:
x_ad = grid_ad_pivot.columns.levels[1].values
y_ad = grid_ad_pivot.index.values
z_ad = grid_ad_pivot.values

# **3D plot AdaBoots**

In [ ]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z_ad, y=y_ad, x=x_ad)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='random_state',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()

# **Hyperparameter tuning bg**

In [ ]:
#Hyperparameter tuning model_Bg
random_state_range = np.arange(1,12,1)
n_estimator_range = np.arange(10,210,10)
param_grid = dict(random_state=random_state_range, n_estimators =n_estimator_range)

bg = BaggingClassifier()


grid_bg = GridSearchCV(estimator=bg, param_grid=param_grid, cv=5 )

In [ ]:
grid_bg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py:802

GridSearchCV(cv=5, estimator=BaggingClassifier(),
             param_grid={'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200]),
                         'random_state': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])})

In [ ]:
print("the best hyperparameters bg model are %s with a score of %0.2f"
      % (grid_bg.best_params_, grid_bg.best_score_))

the best hyperparameters bg model are {'n_estimators': 190, 'random_state': 6} with a score of 0.77


# **dataframe of grid search parameter BG**

In [ ]:
grid_bg_results = pd.concat([pd.DataFrame(grid_bg.cv_results_["params"]),
                          pd.DataFrame(grid_bg.cv_results_["mean_test_score"],
                                       columns=["Accuracy"])],axis=1)
grid_bg_results.head()

n_estimators  random_state  Accuracy
0            10             1  0.742095
1            10             2  0.751200
2            10             3  0.749373
3            10             4  0.749373
4            10             5  0.745738

In [ ]:
grid_bg_contour = grid_bg_results.groupby(['random_state','n_estimators']).mean()
grid_bg_contour

Accuracy
random_state n_estimators          
1            10            0.742095
             20            0.754848
             30            0.756054
             40            0.755450
             50            0.758478
...                             ...
11           160           0.766368
             170           0.768190
             180           0.768190
             190           0.769404
             200           0.770014

[220 rows x 1 columns]

# **pivoting the data bg**

In [ ]:
grid_bg_reset = grid_bg_contour.reset_index()
grid_bg_reset.columns = ['random_state', 'n_estimators', 'Accuracy']
grid_bg_pivot = grid_bg_reset.pivot('random_state', 'n_estimators')
grid_bg_pivot

<ipython-input-86-04e0375e79ad>:3: FutureWarning:

In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.



Accuracy                                                    \
n_estimators       10        20        30        40        50        60    
random_state                                                               
1             0.742095  0.754848  0.756054  0.755450  0.758478  0.762730   
2             0.751200  0.759096  0.764548  0.765762  0.765162  0.761511   
3             0.749373  0.754829  0.757264  0.757264  0.754840  0.762728   
4             0.749373  0.747566  0.757870  0.760912  0.760910  0.760308   
5             0.745738  0.752434  0.756671  0.752414  0.754849  0.750600   
6             0.745755  0.759081  0.761511  0.759691  0.762111  0.763938   
7             0.751812  0.753617  0.758478  0.757261  0.760302  0.760912   
8             0.745138  0.748172  0.758482  0.757274  0.762734  0.765163   
9             0.740877  0.759689  0.758486  0.763937  0.765760  0.762725   
10            0.748759  0.763329  0.760287  0.760890  0.767575  0.767577   
11            0.748774  0.760912  0.761511  0.765145  0.767573  0.765751   

                                                                          \
n_estimators       70        80        90        100       110       120   
random_state                                                               
1             0.764559  0.759698  0.761518  0.763334  0.763336  0.763336   
2             0.759083  0.759696  0.759687  0.763938  0.762120  0.761514   
3             0.761514  0.763332  0.760912  0.762734  0.763944  0.760908   
4             0.759096  0.760916  0.759097  0.760921  0.763345  0.761527   
5             0.750601  0.751814  0.758489  0.759705  0.759092  0.760914   
6             0.766969  0.766363  0.765757  0.768789  0.769397  0.769400   
7             0.762126  0.766980  0.769404  0.766374  0.768190  0.766974   
8             0.763338  0.763340  0.762126  0.763342  0.762130  0.760916   
9             0.763334  0.761509  0.765151  0.761514  0.759691  0.763938   
10            0.762723  0.765154  0.762728  0.759088  0.759689  0.758478   
11            0.768787  0.766359  0.768792  0.766370  0.765156  0.765156   

                                                                          \
n_estimators       130       140       150       160       170       180   
random_state                                                               
1             0.764552  0.760916  0.762732  0.763342  0.764556  0.763946   
2             0.762734  0.762122  0.764550  0.764550  0.764548  0.763336   
3             0.758486  0.762130  0.762736  0.763953  0.761523  0.760306   
4             0.764557  0.763950  0.765165  0.768201  0.765773  0.763345   
5             0.760910  0.762126  0.762126  0.763946  0.764552  0.763946   
6             0.770620  0.768796  0.770616  0.769399  0.767580  0.771217   
7             0.766370  0.766368  0.763938  0.766368  0.765764  0.766976   
8             0.760916  0.761514  0.760906  0.762122  0.762124  0.763334   
9             0.764548  0.763944  0.762730  0.761518  0.765165  0.762736   
10            0.762122  0.760304  0.762728  0.762122  0.763334  0.759086   
11            0.764550  0.763942  0.765152  0.766368  0.768190  0.768190   

                                  
n_estimators       190       200  
random_state                      
1             0.765768  0.766374  
2             0.762732  0.760908  
3             0.760308  0.761523  
4             0.763343  0.763345  
5             0.761518  0.763944  
6             0.773645  0.771823  
7             0.768196  0.768197  
8             0.761514  0.763944  
9             0.766985  0.765163  
10            0.759692  0.763336  
11            0.769404  0.770014

In [ ]:
x_bg = grid_bg_pivot.columns.levels[1].values
y_bg = grid_bg_pivot.index.values
z_bg = grid_bg_pivot.values

# **3D plot bg**

In [ ]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z_bg, y=y_bg, x=x_bg)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='random_state',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()